### ISSUE TITLE
some quick corrections for windows

### ISSUE THREAD

**Issue by eccooper** [fowlmouth/nimrod-enet#1]
I had to make a couple changes to get this working on nim 0.10.2 (current binary dist) on windows:

line 31: `{.deadCodeElim: ON.}` to `{.deadCodeElim: on.}`

line 310: `let ENET_SOCKET_NULL*: cint = INVALID_SOCKET` to `let ENET_SOCKET_NULL*: cint = -1`

because INVALID_SOCKET was not defined for some reason. Just a quick hack [based off  this](http://stackoverflow.com/questions/10817252/why-is-invalid-socket-defined-as-0-in-winsock2-h-c) (it's the same as linux).

**Comment by fowlmouth** [comment]
Hey @eccooper `INVALID_SOCKET` is defined in `winlean`, that line should be `let ENET_SOCKET_NULL*: TENetSocket = winlean.INVALID_SOCKET` and move after the type section
Please send a PR!
